#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

$application = new Symfony\Component\Console\Application(
    'Laravel Webserver Config Generator',
    '1.0.0'
);

$application->add(new Plekhanov\LaravelWebserverConfigGenerator\Commands\GenerateNginxConfigCommand());

$application->run();
